### ISSUE TITLE
Can't update to 0.4.7

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.link#8]
log:
```
$ ./iobroker upgrade link
Update link from @0.4.4 to @0.4.7
NPM version: 6.11.3npm install iobroker.link@0.4.7 --loglevel error --production --save --prefix "/opt/iobroker" (System call)
../src/contextify.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ContextifyContext::New(Nan::NAN_METHOD_ARGS_TYPE)’:../src/contextify.cc:62:74: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]         ContextifyContext* ctx = new ContextifyContext(info[0]->ToObject());                                                                          ^
In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:10046:15: note: declared here Local<Object> Value::ToObject() const {               ^~~~~
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:../src/contextify.cc:131:68: error: no matching function for call to ‘v8::Function::NewInstance()’         Local<Object> wrapper = Nan::New(constructor)->NewInstance();                                                                    ^In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3993:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(                                            ^~~~~~~~~~~/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 0 provided/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3996:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(                                            ^~~~~~~~~~~/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 0 provided
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’; did you mean ‘SetAccessCheckCallback’?         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,                ^~~~~~~~~~~~~~~~~~~~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:../src/contextify.cc:176:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]         Local<Object> data = info.Data()->ToObject();                                                    ^In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:10046:15: note: declared here Local<Object> Value::ToObject() const {               ^~~~~
../src/contextify.cc:182:80: error: no matching function for call to ‘v8::Object::GetRealNamedProperty(v8::Local<v8::String>&)’         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);                                                                                ^
In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3562:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::Context>, v8::Local<v8::Name>)   V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(                                           ^~~~~~~~~~~~~~~~~~~~
/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3562:43: note:   candidate expects 2 arguments, 1 provided
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertySetter(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<v8::Value>&)’:../src/contextify.cc:192:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]         Local<Object> data = info.Data()->ToObject();                                                    ^
In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:10046:15: note: declared here Local<Object> Value::ToObject() const {               ^~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:../src/contextify.cc:203:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]         Local<Object> data = info.Data()->ToObject();                                                    ^
In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:10046:15: note: declared here Local<Object> Value::ToObject() const {               ^~~~~
../src/contextify.cc:209:67: error: no matching function for call to ‘v8::Object::GetRealNamedProperty(v8::Local<v8::String>&)’         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||                                                                   ^In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3562:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::Context>, v8::Local<v8::Name>)   V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(                                           ^~~~~~~~~~~~~~~~~~~~/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3562:43: note:   candidate expects 2 arguments, 1 provided../src/contextify.cc:210:71: error: no matching function for call to ‘v8::Object::GetRealNamedProperty(v8::Local<v8::String>&)’             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {                                                                       ^In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3562:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::Context>, v8::Local<v8::Name>)   V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(                                           ^~~~~~~~~~~~~~~~~~~~/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:3562:43: note:   candidate expects 2 arguments, 1 provided
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyDeleter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Boolean>&)’:../src/contextify.cc:218:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]         Local<Object> data = info.Data()->ToObject();                                                    ^In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:10046:15: note: declared here Local<Object> Value::ToObject() const {               ^~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyEnumerator(const Nan::PropertyCallbackInfo<v8::Array>&)’:../src/contextify.cc:229:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]         Local<Object> data = info.Data()->ToObject();                                                    ^In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:10046:15: note: declared here Local<Object> Value::ToObject() const {               ^~~~~
../src/contextify.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ContextifyScript::RunInContext(Nan::NAN_METHOD_ARGS_TYPE)’:../src/contextify.cc:319:62: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]         if (!ContextifyContext::InstanceOf(info[0]->ToObject()))                                                              ^In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:10046:15: note: declared here Local<Object> Value::ToObject() const {               ^~~~~../src/contextify.cc:322:95: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]         ContextifyContext* ctx = Nan::ObjectWrap::Unwrap<ContextifyContext>(info[0]->ToObject());                                                                                               ^In file included from /home/iobroker/.cache/node-gyp/10.17.0/include/node/node.h:63:0,                 from ../src/contextify.cc:1:/home/iobroker/.cache/node-gyp/10.17.0/include/node/v8.h:10046:15: note: declared here Local<Object> Value::ToObject() const {               ^~~~~
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp
 ERR! build error gyp
 ERR! stack Error: `make` failed with exit code: 2gyp
 ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)gyp ERR! stack     at ChildProcess.emit (events.js:198:13)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)gyp ERR! System Linux 3.10.105
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR!
 cwd /opt/iobroker/node_modules/contextifygyp ERR! node -v v10.17.0gyp ERR! node-gyp -v v5.0.3gyp ERR! not ok 
upload [2] link.admin /opt/iobroker/node_modules/iobroker.link/admin/words.js words.js application/javascript
upload [1] link.admin /opt/iobroker/node_modules/iobroker.link/admin/link.png link.png image/png
upload [0] link.admin /opt/iobroker/node_modules/iobroker.link/admin/index_m.html index_m.html text/html
Adapter "link" updated
process exited with code 0
```

**Comment by Apollon77** [comment]
These are only warning. what exactly is not working?

**Comment by gh-god** [comment]
plz try 0.4.9

**Comment by Anzic23** [comment]
0.4.9 work
